// <auto-generated />
using System;
using ExampleApi.DataSource;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExampleApi.Migrations
{
    [DbContext(typeof(ExampleContext))]
    [Migration("20210421134549_editRole")]
    partial class editRole
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("ExampleApi.Model.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ParentId = 0,
                            Text = "Home",
                            Url = "/index/home"
                        },
                        new
                        {
                            Id = 2,
                            ParentId = 0,
                            Text = "Auth",
                            Url = "Auth"
                        },
                        new
                        {
                            Id = 3,
                            ParentId = 2,
                            Text = "User Manage",
                            Url = "/index/users"
                        },
                        new
                        {
                            Id = 4,
                            ParentId = 2,
                            Text = "Roles Manage",
                            Url = "/index/roles"
                        });
                });

            modelBuilder.Entity("ExampleApi.Model.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authorizer")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Auth = "/index/home |\r\n                             /index/users|\r\n                             /index/roles",
                            CreateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleName = "Admin",
                            UpdateTime = new DateTime(2021, 4, 21, 21, 45, 48, 523, DateTimeKind.Local).AddTicks(7936)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
